### ISSUE TITLE
Schematic would be very helpful

### ISSUE THREAD

**Issue by errmac** [Xinyuan-LilyGO/LilyGO-T-A7670X#12]
Hi,
a schematic or similar documentation of the board (A7670 V 1.1. 2022-2-28) would be very helpful!
I just finished the design of some interface electronic to the board and now I've found that GPIO5
is connected to the modem's reset, which is not documented anywhere as far as I can tell.
So I have to re-design my wiring or de-solder a resistor on the board as stated [here](https://github.com/Xinyuan-LilyGO/LilyGO-T-A7670X/issues/10)
That's pretty annoying...
**So please publish a schematic. This could prevent a lot of painful debugging...** 

Thanks in advance!

**Comment by LilyGO** [comment]
[schematic](https://github.com/Xinyuan-LilyGO/LilyGO-T-A7670X/tree/main/schematic)
