### ISSUE TITLE
Does this device support GPS?

### ISSUE THREAD

**Issue by adriaanvanrossum** [Xinyuan-LilyGO/LilyGO-T-A7670X#2]
Because it has a GPS antenna connector:

![ILYGO-TTGO-T-SIM-A7670E-Module-ESP32-Chip-18650-Battery-Holder-Board-4G-LTE-CAT1-ESP32 jpg_Q90](https://user-images.githubusercontent.com/1079135/136830529-008aa663-10e6-456c-88fb-4d88d4664e87.jpg)

**Comment by demarchidaniele** [comment]
Yes I suppose.
GPS (GNSS) should be a feature of A7670E and it should be supported by TinyGSM library.
Get a look at:
https://github.com/vshymanskyy/TinyGSM/blob/master/src/TinyGsmGPS.tpp
I didn't yet tested but I'll use GPS in the future.

**Comment by LilyGO** [comment]
Hello，The new version already supports GPS

**Comment by adriaanvanrossum** [comment]
What is the new version @LilyGO?

**Comment by LilyGO** [comment]
[new version](https://pt.aliexpress.com/item/1005003036514769.html
![1](https://user-images.githubusercontent.com/31160602/155839894-610764df-8bd5-4f1a-8443-a49acf60a5f3.png)
)
