### ISSUE TITLE
typo in GitHub path

### ISSUE THREAD

**Issue by ClemensGruber** [Xinyuan-LilyGO/LilyGO-T-A7670X#3]
https://github.com/Xinyuan-LilyGO/LilyGO-T-A7670X/tree/main/frimware

frimware should be firmware

**Comment by LilyGO** [comment]
Hello，Is there something wrong?

**Comment by ClemensGruber** [comment]
I think in the directory name `f_ri_mware` is a typo and it should be `f_ir_mware`, means `i` and `r `shold be swapped to write it correct.
