### ISSUE TITLE
Ho can I test GPS?

### ISSUE THREAD

**Issue by FabPari** [Xinyuan-LilyGO/LilyGO-T-A7670X#5]
Hi Dear , Is there an example to test the GPS function?
 try to use your AllFunctions/AllFunctions.ino example but there isn't nothing for the GPS can you help me how to test?
thanks
Fabio

**Comment by LilyGO** [comment]
Hello，Is your board 2021-12-18 V1.0?

**Comment by FabPari** [comment]
Hi dear Where I can found this? 
In the middle of the board is writed T-SIM7000G 20-4-15
behind sim7000x

**Comment by LilyGO** [comment]
This version has no GPS capability

**Comment by FabPari** [comment]
And why there is a GPS port?

**Comment by LilyGO** [comment]
The A7670 package is compatible with SIM7000G.  This version is directly attached to the board of SIM7000 with A7670
