### ISSUE TITLE
Problem about gps/gnss

### ISSUE THREAD

**Issue by emrecanozkok** [Xinyuan-LilyGO/LilyGO-T-A7670X#8]
I bought this board and did some testing. The sd card and gprs feature are working but all my other devices are showing they can't get gps signal where they are working. I'm just running the demo code and I keep getting a blank gps signal message. I need help on this.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/8539564/162338268-b54c44a2-d092-483d-a3f4-af75f08814e8.png">

I could not get results with a different antenna with a long cable.

**Comment by LilyGO** [comment]
Hello. Did you buy the board with GPS support?

**Comment by emrecanozkok** [comment]
> Hello. Did you buy the board with GPS support?

I heated the gps antenna connection and then it started working, but it is more difficult to detect than other modules. Which should I use before starting hot,warm or cold.Is there an adc pin on this module where I can read the battery voltage? and is there a led i can control. I couldn't find a detailed explanation.

**Comment by LilyGO** [comment]
GPIO35可以获取电池的电压

**Comment by emrecanozkok** [comment]
yes you are right im reading voltage when usb plugged it is true but when i disconnect device and run with battery its not read properly its getting everytime 4.2 volt

**Comment by LilyGO** [comment]
float readBattery(uint8_t pin)
{
    int vref = 1100;
    uint16_t volt = analogRead(pin);
    float battery_voltage = ((float)volt / 4095.0) * 2.0 * 3.3 * (vref);
    return battery_voltage;
}

You can refer to this function.  There will be some error because of the partial pressure.  And you get a little bit of an error
